package assesment;

import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author 3100298414
 */
public class FormMain extends javax.swing.JFrame {
    //Initialize & Define Variables
    
    //James' Branch
    
    boolean panel1Visible;
    boolean panel2Visible;
    
    ArrayList<String> comboDefaultArray = new ArrayList();
    ArrayList<String> combo1Array = new ArrayList<>();
    ArrayList<String> combo2Array = new ArrayList<>();
    ArrayList<String> combo3Array = new ArrayList<>();
    ArrayList<String> combo4Array = new ArrayList<>();
    ArrayList<String> combo5Array = new ArrayList<>();
    ArrayList<String> combo6Array = new ArrayList<>();
        
    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        
        //this.setExtendedState(this.getExtendedState() | FormMain.MAXIMIZED_BOTH);
        
        comboDefaultArray.addAll(Arrays.asList("Select An Option..."));
        
        combo1Array.addAll(Arrays.asList("Select An Option...", "Business", "Creaetive Industries", "Health", "Community Services"));
        combo2Array.addAll(Arrays.asList("Select An Option...", "Accounting", "Business", "Human Resources", "Information Technology", "Management", "Tourism & Hospitality"));
        combo3Array.addAll(Arrays.asList("Select An Option...", "Career Pathways", "Essential Employability Skills"));
        combo4Array.addAll(Arrays.asList("Select An Option...", "Cert IV in IT", "Diploma of Software Development", "Diploma of Networking"));
        combo5Array.addAll(Arrays.asList("Select An Option...", "Trainee Application Programmer", "Trainee Business/System's Analyst", "Web Developer", "Trainee Database Programmer", "Trainee Programming Tester", "Trainee Maintenance Programmer", "Articulation Pathway to Bachelor in IT"));
        combo6Array.addAll(Arrays.asList("Select An Option...", "Job Description", "Statistical Data On Demand/Salary Range"));
        
        combo1.setModel(new javax.swing.DefaultComboBoxModel(combo1Array.toArray()));
        combo2.setModel(new javax.swing.DefaultComboBoxModel(comboDefaultArray.toArray()));
        combo3.setModel(new javax.swing.DefaultComboBoxModel(comboDefaultArray.toArray()));
        combo4.setModel(new javax.swing.DefaultComboBoxModel(comboDefaultArray.toArray()));
        combo5.setModel(new javax.swing.DefaultComboBoxModel(comboDefaultArray.toArray()));
        combo6.setModel(new javax.swing.DefaultComboBoxModel(comboDefaultArray.toArray()));
        
        combo2.setEnabled(false);
        combo3.setEnabled(false);
        combo4.setEnabled(false);
        combo5.setEnabled(false);
        combo6.setEnabled(false);
        
        btnSubmit.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        combo4 = new javax.swing.JComboBox();
        combo5 = new javax.swing.JComboBox();
        combo1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        combo2 = new javax.swing.JComboBox();
        combo3 = new javax.swing.JComboBox();
        combo6 = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        combo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        jPanel1.add(combo4, gridBagConstraints);

        combo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        jPanel1.add(combo5, gridBagConstraints);

        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        jPanel1.add(combo1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Find My Career");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 32, 0, 32);
        jPanel1.add(jLabel1, gridBagConstraints);

        jSeparator1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel1.add(jSeparator1, gridBagConstraints);

        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        jPanel1.add(combo2, gridBagConstraints);

        combo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        jPanel1.add(combo3, gridBagConstraints);

        combo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        jPanel1.add(combo6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 10, 0);
        jPanel1.add(jSeparator3, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnExit.setText("Exit");
        btnExit.setMaximumSize(new java.awt.Dimension(65, 28));
        btnExit.setMinimumSize(new java.awt.Dimension(65, 28));
        btnExit.setPreferredSize(new java.awt.Dimension(65, 28));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 0, 0);
        jPanel3.add(btnExit, gridBagConstraints);

        btnSubmit.setText("Submit");
        btnSubmit.setMaximumSize(new java.awt.Dimension(65, 28));
        btnSubmit.setMinimumSize(new java.awt.Dimension(65, 28));
        btnSubmit.setPreferredSize(new java.awt.Dimension(65, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 2);
        jPanel3.add(btnSubmit, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel3, gridBagConstraints);

        jLabel3.setText("Logged In User");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Options...", "Edit Information", "Log Out" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        jPanel1.add(jComboBox2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        if (combo1.getSelectedIndex() != 0) {
            if (combo1.getSelectedItem().toString().equals("Business")) {
                combo2.setEnabled(true);
                combo2.setModel(new javax.swing.DefaultComboBoxModel(combo2Array.toArray()));
            
            }
        } else {
            combo2.setModel(new javax.swing.DefaultComboBoxModel(comboDefaultArray.toArray()));
            combo2.setSelectedIndex(0);
            combo2.setEnabled(false);
        }
    }//GEN-LAST:event_combo1ActionPerformed

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
        if (combo2.getSelectedIndex() != 0) {
            if (combo2.getSelectedItem().toString().equals("Information Technology")) {
                combo3.setEnabled(true);
                combo3.setModel(new javax.swing.DefaultComboBoxModel(combo3Array.toArray()));
            
            }
        } else {
            combo3.setModel(new javax.swing.DefaultComboBoxModel(comboDefaultArray.toArray()));
            combo3.setSelectedIndex(0);
            combo3.setEnabled(false);
        }
    }//GEN-LAST:event_combo2ActionPerformed

    private void combo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo3ActionPerformed
        if (combo3.getSelectedIndex() != 0) {
            if (combo3.getSelectedItem().toString().equals("Career Pathways")) {
                combo4.setEnabled(true);
                combo4.setModel(new javax.swing.DefaultComboBoxModel(combo4Array.toArray()));
            
            }
        } else {
            combo4.setModel(new javax.swing.DefaultComboBoxModel(comboDefaultArray.toArray()));
            combo4.setSelectedIndex(0);
            combo4.setEnabled(false);
        }
    }//GEN-LAST:event_combo3ActionPerformed

    private void combo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo4ActionPerformed
        if (combo4.getSelectedIndex() != 0) {
            if (combo4.getSelectedItem().toString().equals("Diploma of Software Development")) {
                combo5.setEnabled(true);
                combo5.setModel(new javax.swing.DefaultComboBoxModel(combo5Array.toArray()));
            
            }
        } else {
            combo5.setModel(new javax.swing.DefaultComboBoxModel(comboDefaultArray.toArray()));
            combo5.setSelectedIndex(0);
            combo5.setEnabled(false);
        }
    }//GEN-LAST:event_combo4ActionPerformed

    private void combo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo5ActionPerformed
        if (combo5.getSelectedIndex() != 0) {
            if (combo5.getSelectedItem().toString().equals("Trainee Application Programmer")) {
                combo6.setEnabled(true);
                combo6.setModel(new javax.swing.DefaultComboBoxModel(combo6Array.toArray()));
            
            }
        } else {
            combo6.setModel(new javax.swing.DefaultComboBoxModel(comboDefaultArray.toArray()));
            combo6.setSelectedIndex(0);
            combo6.setEnabled(false);
        }
    }//GEN-LAST:event_combo5ActionPerformed

    private void combo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo6ActionPerformed
        if (combo6.getSelectedIndex() != 0) {
            btnSubmit.setEnabled(true);
        
        } else {
            btnSubmit.setEnabled(false);
        }
    }//GEN-LAST:event_combo6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox combo1;
    private javax.swing.JComboBox combo2;
    private javax.swing.JComboBox combo3;
    private javax.swing.JComboBox combo4;
    private javax.swing.JComboBox combo5;
    private javax.swing.JComboBox combo6;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
